-- MySQL Script generated by MySQL Workbench
-- mar 26 oct 2021 10:48:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ProyectAlpha
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProyectAlpha` ;

-- -----------------------------------------------------
-- Schema ProyectAlpha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectAlpha` ;
USE `ProyectAlpha` ;

-- -----------------------------------------------------
-- Table `ProyectAlpha`.`Offers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectAlpha`.`Offers` ;

CREATE TABLE IF NOT EXISTS `ProyectAlpha`.`Offers` (
  `idOffers` INT(20) NOT NULL,
  `enterpriseName` VARCHAR(30) NOT NULL,
  `offerName` VARCHAR(30) NOT NULL,
  `responsibility` LONGTEXT NULL,
  `requirements` LONGTEXT NOT NULL,
  `summary` LONGTEXT NULL,
  `direction` VARCHAR(50) NOT NULL,
  `telephoneNumber` INT(10) NULL,
  `salary` VARCHAR(20) NOT NULL,
  `modality` VARCHAR(20) NOT NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idOffers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectAlpha`.`Technologies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectAlpha`.`Technologies` ;

CREATE TABLE IF NOT EXISTS `ProyectAlpha`.`Technologies` (
  `idTechnologies` INT(20) NOT NULL,
  `tecnologyName` VARCHAR(30) NULL,
  PRIMARY KEY (`idTechnologies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectAlpha`.`Offers_has_Technologies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectAlpha`.`Offers_has_Technologies` ;

CREATE TABLE IF NOT EXISTS `ProyectAlpha`.`Offers_has_Technologies` (
  `Offers_idOffers` INT(20) NOT NULL,
  `Technologies_idTechnologies` INT(20) NOT NULL,
  PRIMARY KEY (`Offers_idOffers`, `Technologies_idTechnologies`),
  INDEX `fk_Offers_has_Technologies_Technologies1_idx` (`Technologies_idTechnologies` ASC) VISIBLE,
  INDEX `fk_Offers_has_Technologies_Offers_idx` (`Offers_idOffers` ASC) VISIBLE,
  CONSTRAINT `fk_Offers_has_Technologies_Offers`
    FOREIGN KEY (`Offers_idOffers`)
    REFERENCES `ProyectAlpha`.`Offers` (`idOffers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offers_has_Technologies_Technologies1`
    FOREIGN KEY (`Technologies_idTechnologies`)
    REFERENCES `ProyectAlpha`.`Technologies` (`idTechnologies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
