-- MySQL Script generated by MySQL Workbench
-- mar 26 oct 2021 16:48:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ProyectAlpha
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ProyectAlpha` ;

-- -----------------------------------------------------
-- Schema ProyectAlpha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectAlpha` ;
USE `ProyectAlpha` ;

-- -----------------------------------------------------
-- Table `ProyectAlpha`.`Configuration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectAlpha`.`Configuration` ;

CREATE TABLE IF NOT EXISTS `ProyectAlpha`.`Configuration` (
  `id` INT NOT NULL,
  `salary` VARCHAR(20) NOT NULL,
  `modality` VARCHAR(20) NOT NULL,
  `date` DATE NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectAlpha`.`Offers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectAlpha`.`Offers` ;

CREATE TABLE IF NOT EXISTS `ProyectAlpha`.`Offers` (
  `id` INT(20) NOT NULL,
  `enterprise_name` VARCHAR(30) NOT NULL,
  `offer_name` VARCHAR(30) NOT NULL,
  `responsibility` LONGTEXT NULL,
  `requirements` LONGTEXT NOT NULL,
  `summary` LONGTEXT NULL,
  `configuration_id` INT NOT NULL,
  PRIMARY KEY (`id`, `configuration_id`),
  INDEX `fk_Offers_Configuration1_idx` (`configuration_id` ASC) VISIBLE,
  CONSTRAINT `fk_Offers_Configuration1`
    FOREIGN KEY (`configuration_id`)
    REFERENCES `ProyectAlpha`.`Configuration` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectAlpha`.`Technologies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectAlpha`.`Technologies` ;

CREATE TABLE IF NOT EXISTS `ProyectAlpha`.`Technologies` (
  `id` INT(20) NOT NULL,
  `name` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectAlpha`.`Offers_has_Technologies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProyectAlpha`.`Offers_has_Technologies` ;

CREATE TABLE IF NOT EXISTS `ProyectAlpha`.`Offers_has_Technologies` (
  `offers_id` INT(20) NOT NULL,
  `tecnologies_id` INT(20) NOT NULL,
  PRIMARY KEY (`offers_id`, `tecnologies_id`),
  INDEX `fk_Offers_has_Technologies_Technologies1_idx` (`tecnologies_id` ASC) VISIBLE,
  INDEX `fk_Offers_has_Technologies_Offers_idx` (`offers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Offers_has_Technologies_Offers`
    FOREIGN KEY (`offers_id`)
    REFERENCES `ProyectAlpha`.`Offers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offers_has_Technologies_Technologies1`
    FOREIGN KEY (`tecnologies_id`)
    REFERENCES `ProyectAlpha`.`Technologies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
